figure (1)
subplot(3,1,1)
plot(all_data(:,22),all_data(:,10))
xlabel('time (sec)')
ylabel('u (ft/sec)')
subplot(3,1,2)
plot(all_data(:,22),all_data(:,11))
xlabel('time (sec)')
ylabel('v (ft/sec)')
subplot(3,1,3)
plot(all_data(:,22),all_data(:,12))
xlabel('time (sec)')
ylabel('w (ft/sec)')

figure (2)
subplot(3,1,1)
plot(all_data(:,22),all_data(:,13))
xlabel('time (sec)')
ylabel('p (rad/sec)')
subplot(3,1,2)
plot(all_data(:,22),all_data(:,14))
xlabel('time (sec)')
ylabel('q (rad/sec)')
subplot(3,1,3)
plot(all_data(:,22),all_data(:,15))
xlabel('time (sec)')
ylabel('r (rad/sec)')

phi=180/pi()*all_data(:,7);
theta=180/pi()*all_data(:,8);
zeta=180/pi()*all_data(:,9);
figure (3)
subplot(3,1,1)
plot(all_data(:,22),phi)
xlabel('time (sec)')
ylabel('phi (deg)')
subplot(3,1,2)
plot(all_data(:,22),theta)
xlabel('time (sec)')
ylabel('theta (deg)')
subplot(3,1,3)
plot(all_data(:,22),zeta)
xlabel('time (sec)')
ylabel('zeta (deg)')


figure (4)
subplot(3,1,1)
plot(all_data(:,22),all_data(:,4))
xlabel('time (sec)')
ylabel('Xe (ft)')
subplot(3,1,2)
plot(all_data(:,22),all_data(:,5))
xlabel('time (sec)')
ylabel('Ye (ft)')
subplot(3,1,3)
plot(all_data(:,22),all_data(:,6))
xlabel('time (sec)')
ylabel('Ze (ft)')

